Bulding an emotion detection model using KNN. Emotion detection model using KNN is actually inefficient since KNN checks your input with every dataset it has stored, this is done for the sake trying things out

Pipeline : Sentence -> Vectorization -> KNN -> Emotion prediction

First we have analyse the dataset we are working with

In [1]:
import pandas as pd
df=pd.read_csv("emotion_dataset.csv")
df.head()

                          text  emotion
0                I am thrilled  excited
1  Just another regular moment  neutral
2    Nothing special happening  neutral
3        I hate this situation    angry
4          This is so exciting  excited

In [2]:
df.shape

(300, 2)

We have 300 rows with 2 columns

Let's vectorize the text input data

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
vectorizer = TfidfVectorizer(
    max_features=500,
    stop_words='english',
    ngram_range=(1,2)
)
X=vectorizer.fit_transform(df["text"])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 856 stored elements and shape (300, 64)>

In [50]:
vectorizer.get_feature_names_out()

array(['amazing', 'amazing right', 'angry', 'angry right', 'beautiful',
       'best', 'best day', 'day', 'depressed', 'excited', 'exciting',
       'feel', 'feel amazing', 'feel lonely', 'feel sad', 'feeling',
       'feeling great', 'feels', 'feels right', 'forward', 'frustrating',
       'furious', 'going', 'going store', 'great', 'great today',
       'happening', 'happy', 'happy excited', 'hate', 'hate situation',
       'just', 'just regular', 'life', 'life beautiful', 'lonely',
       'lonely depressed', 'looking', 'looking forward', 'mad', 'makes',
       'makes mad', 'meeting', 'meeting today', 'moment', 'normal',
       'normal day', 'really', 'really angry', 'regular',
       'regular moment', 'right', 'sad', 'situation', 'special',
       'special happening', 'store', 'super', 'super excited', 'terrible',
       'terrible day', 'thrilled', 'today', 'wait'], dtype=object)

In [51]:
y=df["emotion"]
y

0      excited
1      neutral
2      neutral
3        angry
4      excited
        ...
295    neutral
296        sad
297      angry
298      angry
299      happy
Name: emotion, Length: 300, dtype: object

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [37]:
model=KNeighborsClassifier(n_neighbors=5,metric="cosine")
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
model.fit(X_train,y_train)

KNeighborsClassifier(metric='cosine')

In [39]:
acc=accuracy_score(y_test,model.predict(X_test))
print("Accuracy score : "+str(acc*100)+"%")

Accuracy score : 100.0%

Overfitting model

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentence="I am furious"
vectorizer = TfidfVectorizer(
    max_features=500,
    stop_words='english',
    ngram_range=(1,2)
)
X = vectorizer.fit_transform(df["text"])
sentence_vectorized = vectorizer.transform([sentence])
print(model.predict(sentence_vectorized))

['angry']

In [52]:
while True:
    n=input("Enter a sentence :")
    if n=="bye":
        print("Bye")
        break
    n=vectorizer.transform([n])
    print("I think you are : "+model.predict(n))

Enter a sentence :i am angry
['I think you are : angry']
Enter a sentence :i am very sad you know
['I think you are : sad']
Enter a sentence :i am so happy
['I think you are : happy']
Enter a sentence :i hate you
['I think you are : angry']
Enter a sentence :bye
Bye

Since it is an overfitting model, let's try to improvise it by increasing the neighbors

In [53]:
model = KNeighborsClassifier(
    n_neighbors=5,
    weights='distance'
)
model.fit(X_train,y_train)

KNeighborsClassifier(weights='distance')

In [54]:
str(accuracy_score(y_test,model.predict(X_test))*100)+"%"

'100.0%'

This seems like it could be solved if the dataset are increased since we tried removing the " stop words like "is,am,are" using tfidf vectorizer and using 5 neighbors"